version: "3"
services:
  app:
    image: app-stream
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/app   
      - ./node_modules:/app/node_modules 
    command: bash -c "npm run start:dev"